---
- name: install nginx
  become: yes
  dnf:
    name: nginx
    state: latest
  notify: restart_nginx

- name: copy nginx conf
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart_nginx
